fix: move proposal rpc to authrpc to prevent unauthorized access
```test
$ cast rpc --rpc-url http://127.0.0.1:8551 consensusExt_proposals
Error: HTTP error 401 with body: Authorization header is missing or
invalid

Context:
- HTTP error 401 with body: Authorization header is missing or invalid

$ cast rpc --rpc-url http://127.0.0.1:8551 --jwt-secret xxx-secret consensusExt_proposals
{}
```